### ISSUE TITLE
NodeJS failes to attach message

### ISSUE THREAD

**Issue by antonionardella** [xdk2mam/xdk2mam#7]
Hello,

I am using xdk2mam-mqtt.
The xdk2mam-nodejs gives following error:
```
** Data:  {"xdk2mam":[{"sensor": "Environmental","data":[{"Pressure":"98052"},{"Temp":"29270"},{"Humidity":"34"}]},{"sensor":"Accel","data":[{"x":"12"},{"y":"-64"},{"z":"1038"}]},{"sensor":"Gyroscope","data":[{"x":"3538"},{"y":"-1220"},{"z":"-8052"}]},{"sensor":"Inertial","data":[{"x":"-122"},{"y":"244"},{"z":"366"}]},{"sensor":"Light","data":[{"milliLux":"13320"}]},{"sensor":"Magnetometer","data":[{"x":"29"},{"y":"-12"},{"z":"-45"}]},{"sensor":"Acoustic","data":[{"mp":"0.009903"}]} ],"device": "STODTXDK01","timestamp": "517"}

** Root:  IQSULKNPBRNMUWGJI9U9ADIANEDSLVHAFVSYDYBKSEWOHXLHPMWZJBEIQNYAGVUKPZFLBAQTHAKKLDOOV
failed to attach message: 
 Error: Request Error: Invalid depth input
    at Object.requestError (/home/node/xdk2mam/node_modules/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/home/node/xdk2mam/node_modules/iota.lib.js/lib/utils/makeRequest.js:293:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/node/xdk2mam/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/node/xdk2mam/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/node/xdk2mam/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/node/xdk2mam/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

It looks like the depht is not correct:
```
Error: Request Error: Invalid depth input
```

Cheers,
Antonio

**Comment by antonionardella** [comment]
This was solved using a different node.
